//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xml_config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public xml_config()
        {
            this.xml_config1 = new HashSet<xml_config>();
        }
    
        public string xml_config_guid { get; set; }
        public string client_guid { get; set; }
        public string root_xml_config_guid { get; set; }
        public string xml_data { get; set; }
        public Nullable<int> lkp_xml_source_id { get; set; }
        public Nullable<bool> edit { get; set; }
        public Nullable<int> process_count { get; set; }
        public Nullable<int> size { get; set; }
        public string hash { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<xml_config> xml_config1 { get; set; }
        public virtual xml_config xml_config2 { get; set; }
    }
}
